version: "2.0"
services:
  app:
    container_name: ${PROJECT_NAME}-app
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - GITHUB_TOKEN
    depends_on:
      - db
      - elasticsearch
      - redis
      - rabbitmq
      - jenkins
    ports:
      - "80:8080"
      - "10001:10001"
      - "222:222"
    environment:
      ENV_NAME: dockersuite
      APPLICATION_ENV: development
      APPLICATION_STORE: ESA
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: spryker
      POSTGRES_PASSWORD: mate20mg
      PGPASSWORD: mate20mg
      POSTGRES_DATABASE: ESA_development_zed
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PROTOCOL: redis
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_API_PORT: 15672
      RABBITMQ_USER: spryker
      RABBITMQ_PASSWORD: mate20mg
      RABBITMQ_VHOST: /ESA_development_zed
      YVES_HOST: www.esa.suite.local
      YVES_PROTOCOL: http
      ZED_HOST: zed.esa.suite.local
      ZED_PROTOCOL: http
      JENKINS_HOST: jenkins
      JENKINS_PORT: 8080
      GLUE_HOST: glue.esa.suite.local
      NEWRELIC_KEY: eu01xx66d6d4f1e2a4d9c3509626584fd4fa5303
      GITHUB_TOKEN: 8888yourgithubtoken8888
      PHP_CLI_RAM: 2048
      SMTP_HOST: 127.0.0.1
      SMTP_PORT: 25
      SMTP_USER: ''
      SMTP_PASS: ''
      SMTP_TLS: 'no'
      ZED_HTTPS_ON: 0
      ZED_HTTP_TO_HTTPS: 0
      YVES_HTTPS_ON: 0
      YVES_HTTP_TO_HTTPS: 0
      GLUE_HTTPS_ON: 0
      GLUE_HTTP_TO_HTTPS: 0
      PHP_IDE_CONFIG: serverName=zed
      XDEBUG_CONFIG: xdebug.remote_host=192.168.103.110 remote_port=9009 remote_autostart=1
    volumes:
        - ../current:/data/shop/development/current:rw

  db:
    container_name: ${PROJECT_NAME}-db
    image: postgres:9.6
    environment:
      POSTGRES_DB: ESA_development_zed
      POSTGRES_USER: spryker
      POSTGRES_PASSWORD: mate20mg
    ports:
      - "5432:5432"

  elasticsearch:
    container_name: ${PROJECT_NAME}-elasticsearch
    image: elasticsearch:5.6
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data

  redis:
    container_name: ${PROJECT_NAME}-redis
    image: redis:3.2
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data

  rabbitmq:
    container_name: ${PROJECT_NAME}-rabbitmq
    image: rabbitmq:3.7-management
    environment:
      RABBITMQ_DEFAULT_USER: spryker
      RABBITMQ_DEFAULT_PASS: mate20mg
      RABBITMQ_DEFAULT_VHOST: /ESA_development_zed
    ports:
      - "15672:15672"
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data

  jenkins:
    container_name: ${PROJECT_NAME}-jenkins
    build:
      context: .
      dockerfile: jenkins/Dockerfile
    environment:
      JAVA_OPTS: '-Djenkins.install.runSetupWizard=false'
      ZED_HOST: app
    ports:
      - "9090:8080"
    volumes:
      - ../current:/data/shop/development/current:rw

volumes:
  versions-sync:
    external: true
  static-sync:
    external: true
  jenkins-sync:
    external: true
